-- .=========================.
-- | CREATE TABLES           |
-- :=========================:
-- | Agent                   |
-- | Stage                   |
-- | Band                    |
-- | Member                  |
-- | Performance             |
--  =========================
DROP TABLE Performance;
DROP TABLE Stage;
DROP TABLE Member;
DROP TABLE Band;
DROP TABLE Agent;
DROP TABLE Crud_users;


-- Agent
CREATE TABLE Agent (
  ID INT NOT NULL AUTO_INCREMENT,
  GivenName VARCHAR(20) NOT NULL,
  FamilyName VARCHAR(30) NOT NULL,
  Contact VARCHAR(15) NOT NULL,
  PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

-- Stage
CREATE TABLE Stage (
  ID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(20) NOT NULL UNIQUE,
  Capacity INT NOT NULL,
  quantityLive INT NOT NULL,
  PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

-- Band
CREATE TABLE Band (
  ID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(20) NOT NULL UNIQUE,
  Description VARCHAR(20) NOT NULL,
  AgentID INT NOT NULL,
  PRIMARY KEY (ID),
  INDEX (AgentID),
  FOREIGN KEY (AgentID)
    REFERENCES Agent(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
  )ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

-- Crud_users
CREATE TABLE Crud_users (
  ID INT NOT NULL AUTO_INCREMENT,
  Username VARCHAR(70) NOT NULL,
  Password VARCHAR(70) NOT NULL,
  Permissions VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
  )ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

-- Member
CREATE TABLE Member (
  ID INT NOT NULL AUTO_INCREMENT,
  Title VARCHAR(20),
  GivenName VARCHAR(20) NOT NULL,
  FamilyName VARCHAR(30) NOT NULL,
  JobType VARCHAR(20),
  Band INT NOT NULL,
  Status VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID),
  INDEX(Band),
  FOREIGN KEY(Band)
    REFERENCES Band(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
  )ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

-- Performance
CREATE TABLE Performance (
  ID INT NOT NULL AUTO_INCREMENT,
  Stage INT NOT NULL,
  Date DATE NOT NULL,
  Time TIME NOT NULL,
  Band INT NOT NULL,
  PRIMARY KEY (ID),
  INDEX (Band),
  INDEX (Stage),
  FOREIGN KEY (Band)
    REFERENCES Band(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (Stage)
    REFERENCES Stage(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
